name: clip_api
channels:
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - arrow-cpp=19.0.0
  - attrs=24.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.3
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.2
  - aws-c-io=0.20.1
  - aws-c-mqtt=0.13.2
  - aws-c-s3=0.8.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.10
  - aws-sdk-cpp=1.11.528
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - certifi=2025.7.14
  - cffi=1.17.1
  - datasets=3.3.2
  - dill=0.3.8
  - expat=2.7.1
  - frozenlist=1.5.0
  - gflags=2.2.2
  - glog=0.5.0
  - huggingface_hub=0.31.2
  - icu=73.1
  - libabseil=20250127.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.14.1
  - libcxx=17.0.6
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libgrpc=1.71.0
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libopenblas=0.3.29
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libssh2=1.11.1
  - libthrift=0.15.0
  - llvm-openmp=17.0.6
  - lz4-c=1.9.4
  - multidict=6.1.0
  - multiprocess=0.70.15
  - ncurses=6.5
  - numexpr=2.11.0
  - numpy-base=2.0.1
  - openssl=3.0.17
  - orc=2.1.1
  - packaging=25.0
  - pandas=2.3.1
  - pip=25.1
  - propcache=0.3.1
  - protobuf=5.29.3
  - pyarrow=19.0.0
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.11.13
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - re2=2024.07.02
  - readline=8.2
  - requests=2.32.4
  - safetensors=0.5.3
  - setuptools=78.1.1
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.50.2
  - tk=8.6.14
  - tqdm=4.67.1
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - wheel=0.45.1
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.18.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - accelerate==1.9.0
      - addict==2.4.0
      - asttokens==3.0.0
      - charset-normalizer==3.4.2
      - clip==1.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - decorator==5.2.1
      - defusedxml==0.7.1
      - einops==0.8.1
      - executing==2.2.0
      - filelock==3.18.0
      - fonttools==4.59.0
      - fsspec==2025.7.0
      - ftfy==6.3.1
      - h5py==3.14.0
      - hf-xet==1.1.5
      - huggingface-hub==0.34.3
      - idna==3.10
      - imageio==2.37.0
      - ipython==9.4.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - matplotlib-inline==0.1.7
      - mlx==0.27.1
      - mlx-metal==0.27.1
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.3.8
      - prompt-toolkit==3.0.51
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycocotools==2.0.10
      - pygments==2.19.2
      - pyparsing==3.2.3
      - regex==2025.7.34
      - scikit-image==0.25.2
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - sentence-transformers==5.0.0
      - sentencepiece==0.2.0
      - setproctitle==1.3.6
      - sglang==0.4.10.post1
      - stack-data==0.6.3
      - supervision==0.26.1
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tifffile==2025.6.11
      - timm==1.0.19
      - tokenizers==0.21.4
      - torch==2.7.1
      - torchvision==0.22.1
      - traitlets==5.14.3
      - transformers==4.54.1
      - typing-extensions==4.14.1
      - wcwidth==0.2.13
      - yapf==0.43.0
